# SPDX-FileCopyrightText: Copyright (c) 2025 Cisco and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0

name: CI/CD Pipeline

on:
  push:
    tags:
      - 'v*.*.*'

  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    name: Prepare
    outputs:
      release_tag: ${{ steps.vars.outputs.release_tag }}
    runs-on: ubuntu-latest
    steps:
      - name: Resolve required vars
        id: vars
        run: |
          echo "release_tag=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"

  docs:
    name: Docs
    needs:
      - prepare
    uses: ./.github/workflows/reusable-docs.yml
    permissions:
      contents: read
      pages: write
      id-token: write
    with:
      deploy: ${{ startsWith(github.ref, 'refs/tags/') }}
      version: ${{ needs.prepare.outputs.release_tag }}

  success:
    name: Success
    if: ${{ !cancelled() && !contains(needs.*.result, 'cancelled') && !contains(needs.*.result, 'failure') }}
    needs:
      - prepare
      - docs
    runs-on: ubuntu-latest
    steps:
      - name: Echo Success
        run: echo "::notice Success!"
